global:
  instanceName: instance name
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 10
  maxDistance: 5
  allowlist:
    - "185221222119"
    - 5c456XXXXf78
    - dc0efXXXX203
homeAssistant:
  mqttUrl: 'mqtt://IP.IP.IP.10:1883'
  mqttOptions:
    username: user
    password: password
cluster:
  autoDiscovery: false
  networkInterface: eth0
#  port: 6425
  weight: 5
  peerAddresses:
    - IP.IP.IP.7:6425
    - IP.IP.IP.6:6425
    - IP.IP.IP.5:6425
